### ISSUE TITLE
harmonize gh-actions

### ISSUE THREAD

**Issue by earloc** [earloc/postomate#1]
Currently, there are two build-yamls, which only differ in their trigger:

# main.yaml
```yaml

on:
  push:
    branches: [ main ]

```

# pullrequests.yaml
```yaml

on:
  pull_request:
    branches: [ main ]

```

this should be harmonized somehow:
- restore packages
- build
- test
- upload coverage-report

Later, there should also be some steps/actions for pushing everything into NuGet, but that is probably a new gh-actions?!
